# Generated by Django 6.0.6 on 2026-06-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='course_name',
            field=models.CharField(blank=True, help_text='The specific program (e.g., BCA, BSc Computer Science, BCom, MCA, MSc, etc.)', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='education_tier',
            field=models.CharField(choices=[('ENTRANCE', 'Entrance Exam Prep'), ('SCHOOL_KERALA', 'School - Kerala State Syllabus'), ('SCHOOL_CBSE', 'School - CBSE'), ('UG', 'Undergraduate (UG) Course'), ('PG', 'Postgraduate (PG) Course'), ('OTHER', 'General / Other Resource')], default='ENTRANCE', help_text="Categorizes this document's educational track", max_length=30),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='grade_or_semester',
            field=models.CharField(blank=True, help_text="e.g., 'Class 5', 'Class 10', 'BCA Semester 3', 'MSc Physics Semester 1'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='subject',
            field=models.CharField(blank=True, help_text='e.g., Mathematics, Computer Science, Biology, Chemistry, Malayalam', max_length=150, null=True),
        ),
    ]
